### ISSUE TITLE
ResourceCollection with included

### ISSUE THREAD

**Issue by wdmeeste1** [scott-mcdonald/JsonApiFramework#29]
How can you use the included on a resourcollection?

**Example situation**

I have a list of samples and every sample has one sample type. 

I want to get all the samples (localhost/samples) and in the included field I want to see the information of the used types that are connected with every sample.

**Sample.cs (IResource)**

```
public class Sample : IResource
    {
        public string Name { get; set; }

        public virtual SampleType SampleType { get; set; }
    }
```
SampleType.cs has only a name attribute.

**Configuration**

```
public class SampleConfiguration : ResourceTypeBuilder<Sample>
    {
        public SampleConfiguration()
        {
            this.ResourceIdentity(x => x.ID).SetApiType("Sample");

            this.Attribute(x => x.Name).SetApiPropertyName("Name");

            this.ToOneRelationship<SampleType>("SampleType");
        }
    }

    public class SampleTypeConfiguration : ResourceTypeBuilder<SampleType>
    {
        public SampleTypeConfiguration()
        {
            this.ToManyRelationship<Sample>("Samples");
        }
    }
```

**Create document**
```
private string createJson(List<Sample> data){
    var document =new ApplicationDocumentContext()
                .NewDocument("url")
                            .Links()
                                .AddUpLink()
                                .AddSelfLink()
                            .LinksEnd()
                            .ResourceCollection(data)

                                .Relationships()
                                    .AddRelationship("SampleType", Keywords.Related)
                                .RelationshipsEnd()

                                .Links()
                                    .AddSelfLink()
                                .LinksEnd()
                            .ResourceCollectionEnd()

                            .Included()
                                .ToOne(?????)
                                .ToOneEnd()
                            .IncludedEnd()
                            ;
            return document.WriteDocument().ToJson();
}
```
**Result**

```
{
  "links": {
    "up": "http://localhost:5000",
    "self": "http://localhost:5000/api"
  },
  "data": [
    {
      "type": "Sample",
      "id": "2",
      "attributes": {
        "Name": "123"
      },
      "relationships": {
        "SampleType": {
          "links": {
            "related": "http://localhost:5000/api/samples/2/SampleType"
          },
          "data": null
        },
    },
    {
      "type": "Sample",
      "id": "4",
      "attributes": {
        "Name": "456"
      },
      "relationships": {
        "SampleType": {
          "links": {
            "related": "http://localhost:5000/api/samples/4/SampleType"
          },
          "data": null
        }
    }
  ]
}

```

**Comment by scott-mcdonald** [comment]
I acknowledge that the documentation is lacking compared to all the features the framework has. I am focusing on version 2.0 and when finished in the coming months plan on adding to the documentation things such as all the flavors of the document building features.

So what you are asking for is easy, try something like the following:

```csharp

var sampleCollection = GetSampleCollection();

var sampleToSampleTypeResourceLinkage = sampleCollection
    .Select(x => ToOneResourceLinkage.Create(x, "SampleType", x.SampleType))
    .ToList();

// If sample type can be null, them maybe something like this as an alternative
var sampleToSampleTypeResourceLinkage = sampleCollection
    .Where(x => x.SampleType != null)
    .Select(x => ToOneResourceLinkage.Create(x, "SampleType", x.SampleType))
    .ToList();

var currentUrl = HttpContext.Current.Request.Url;
var document = new ApplicationDocumentContext(currentUrl)
    .NewDocument(currentUrl)
        .Links()
            .AddUpLink()
            .AddSelfLink()
        .LinksEnd()
        .ResourceCollection(data)
            .Relationships()
                .AddRelationship("SampleType", Keywords.Related)
            .RelationshipsEnd()
    
            .Links()
                .AddSelfLink()
            .LinksEnd()
        .ResourceCollectionEnd()
        .Included()
            .ToOne(sampleToSampleTypeResourceLinkage)
                .Links()
                    .AddSelfLink()
                .LinksEnd()
            .ToOneEnd()
        .IncludedEnd()
    .WriteDocument();

var json = document.ToJson();

```

FYI: There is also a `ToManyResourceLinkage.Create(fromResource, rel, IEnumerable<T> toResourceCollection)` for to-many relationships.

**Comment by wdmeeste1** [comment]
Thxs for the answer. 

Now I have the following error (because multiple samples can have the same sample type):

```
An unhandled exception has occurred: An item with the same key has already been added. Key: ResourceIdentifier [type=SampleType id=1]
System.ArgumentException: An item with the same key has already been added. Key: ResourceIdentifier [type=SampleType id=1]
```

Is there a solution for this?

**Comment by scott-mcdonald** [comment]
This was identified in #23 where related resources referenced multiple times is a valid, legal scenario in which the framework should handle gracefully. So this was already fixed. What version of JsonApiFramework are you using?

The bug #23 was fixed with v1.3-beta, the current nuget.org version is v1.2-beta. Please make sure you have the latest version and if this is still an issue I will address it immediately.

**Comment by wdmeeste1** [comment]
I switched back to the 1.1.3-beta (I was on the v1.2.0-beta) and it works!
Seems this bug is back in the newer version?

**Comment by scott-mcdonald** [comment]
@wdmeeste1 I have verified the fix is in v1.2.0-beta and the unit test pasts. I also used my own sample project to reproduce and verify the defect in previous v1.1.2-beta and earlier versions and also verified the fix works in both v1.1.3-beta and v1.2.0-beta versions of the framework.

Is your project on github where I can see the code and see what is happening? Or can you write a unit test in reproduce the defect? I want to fix this ASAP...

Thanks,
Scott

**Comment by scott-mcdonald** [comment]
Going to close this as I feel this is already fixed.
